config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  root "home#index"

  get "/matlab", to: "matlab#index"

  get "/get_zip", to: "matlab#get_zip"
  get "/get_zip_ok", to: "matlab#get_zip_ok"

  get "/read_dicom_header", to: "matlab#read_dicom_header"
  get "/read_dicom_header_ok", to: "matlab#read_dicom_header_ok"

  get "/start_matlab", to: "matlab#start_matlab"
  get "/start_matlab_ok", to: "matlab#start_matlab_ok"

  get "/add_pdf_to_db", to: "matlab#add_pdf_to_db"
  get "/add_pdf_to_db_ok", to: "matlab#add_pdf_to_db_ok"

  get "/remove_dicom_entry", to: "matlab#remove_dicom_entry"
  get "/remove_dicom_entry_ok", to: "matlab#remove_dicom_entry_ok"

  get "/finished", to: "matlab#finished"
  

  resources :spms
  resources :patients
  resources :settings

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
    validates :key, presence: true
    validates :key, uniqueness: true
    validates :value, presence: true
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    before_action :find_setting, only: [:show, :edit, :update, :destroy]

    def index
        @settings = Setting.order(:key).page(params[:page])
    end

    def show
    end

    def new
        @setting = Setting.new
    end

    def create
        @setting = Setting.create(setting_params)
        if @setting.save
            flash[:notice] = "Settings created"
            redirect_to settings_path
        else
            flash[:alert] = "Error(s)"
            render :new
        end
    end

    def edit
    end

    def update
        if @setting.update(setting_params)
            flash[:notice] = "Settings updated."
            redirect_to settings_path
        else
            render :edit
        end
    end

    def destroy
        @setting.destroy
    end

    private

    def setting_params
        params.require(:setting).permit(:key, :value)
    end

    def find_setting
        @setting = Setting.find(params[:id])
    end
    
end

app/views/settings/_form.html.erb
<%= form_with model: @setting, local: true do |form| %>

    <% if @setting.errors.any? %>
        <strong>WARNING</strong>
        <ul>
            <% @setting.errors.full_messages.each do |message| %>
                <li class="bg-danger"><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    
    <!-- Key -->
    <p>
        <%= form.label :key %><br>
        <%= form.text_field :key, placeholder: "Key" %>
    </p>

    <!-- Value -->
    <p>
        <%= form.label :value %><br>
        <%= form.text_field :value, placeholder: "Value" %>
    </p>

    <p>
        <%= form.submit class: "btn btn-primary" %>
    </p>

<% end %>

app/views/settings/_setting.html.erb
<tr id="setting_<%= setting.id %>">

    <td>[<%= setting.key %>]</td>

    <td>"<%= setting.value %>"</td>

    <td><a href="<%= edit_setting_path(setting) %>" class="btn btn-info btn-sm" role="button"
            data-toggle="tooltip" title="Edit setting">
            <span class="material-icons">edit</span>
        </a></td>
    
    <td><%= link_to '<span class="material-icons" data-toggle="tooltip" title="Delete">clear</span>'.html_safe, 
            setting_path(setting),
            method: :delete,
            remote: true,
            data: { confirm: "Delete setting #{setting.key} ?" },
            class: "btn btn-danger btn-sm" 
        %></td>

    
</tr>

app/views/settings/_settings.html.erb
<!-- Table paginée -->
<p><%= paginate @settings, remote: true %></p>
<table class="table table-striped">
    <tr>
        <th>Key</th>
        <th>Value</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <%= render @settings %>
</table>
<p><%= paginate @settings, remote: true %></p>

app/views/settings/destroy.js.erb
$("#setting_<%= @setting.id %>").remove();

app/views/settings/edit.html.erb
<h3>Edit Setting</h3>
<%= render "form" %>

app/views/settings/index.html.erb
<h1>Settings</h1>

<p>
    <a href="<%= new_setting_path %>" class="btn btn-secondary" role="button"
        data-toggle="tooltip" title="New Setting">
        <span class="material-icons">add</span>
    </a>
</p>

<div id="settings">
    <%= render 'settings' %>
</div>

app/views/settings/index.js.erb
$("#settings").html("<%= j render "settings" %>");

app/views/settings/new.html.erb
<h3>New Setting</h3>
<%= render "form" %>