config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  root "home#index"

  get "/matlab", to: "matlab#index"

  get "/get_zip", to: "matlab#get_zip"
  get "/get_zip_ok", to: "matlab#get_zip_ok"

  get "/read_dicom_header", to: "matlab#read_dicom_header"
  get "/read_dicom_header_ok", to: "matlab#read_dicom_header_ok"

  get "/start_matlab", to: "matlab#start_matlab"
  get "/start_matlab_ok", to: "matlab#start_matlab_ok"

  get "/add_pdf_to_db", to: "matlab#add_pdf_to_db"
  get "/add_pdf_to_db_ok", to: "matlab#add_pdf_to_db_ok"

  get "/remove_dicom_entry", to: "matlab#remove_dicom_entry"
  get "/remove_dicom_entry_ok", to: "matlab#remove_dicom_entry_ok"

  get "/finished", to: "matlab#finished"
  

  resources :spms
  resources :patients
  resources :settings

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/matlab_controller.rb
class MatlabController < ApplicationController
    before_action :get_camera, only: [:index, :start_matlab]
    before_action :get_config, only: [:get_zip_ok, :start_matlab_ok, :add_pdf_to_db_ok, :remove_dicom_entry_ok]

    #############
    #   INDEX   #
    #############
    def index
        @progression = get_progression(1, 13)
    end


    #########################
    #   READ DICOM HEADER   #
    #########################
    def read_dicom_header
        @progression = get_progression(2, 13)
        session[:camera] = params[:camera] if params[:camera]
    end

    def read_dicom_header_ok
        @progression = get_progression(3, 13)
        @res = false

        # liste patients
        patients = find_orthanc_patients
        if patients

            # dernier patient
            dernier_patient = find_orthanc_dernier_patient(patients[patients.length-1])
            session[:orthanc_patient_id]
            patient_studies = dernier_patient["Studies"]
            dernier_patient = dernier_patient["MainDicomTags"]

            if dernier_patient

                # patient id
                patient_id = dernier_patient["PatientID"]
                patient_name = dernier_patient["PatientName"]

                if patient_id and patient_name and patient_studies
                    session[:patient_id] = patient_id
                    session[:patient_name] = patient_name

                    # last study
                    patient_study = patient_studies[patient_studies.length-1]
                    patient_study = find_orthanc_study(patient_study)
                    patient_study = patient_study["MainDicomTags"]
                    patient_study_date = patient_study["StudyDate"]
                    if patient_study_date
                        session[:study_date] = patient_study_date
                        @res = true
                    end
                end
            end
        end
    end


    #################
    #   GET ZIP     #
    #################
    def get_zip
        @progression = get_progression(5, 13)
    end

    def get_zip_ok
        @progression = get_progression(6, 13)
        @res = false

        # liste patients
        patients = find_orthanc_patients
        if patients

            # dernier patient
            dernier_patient = find_orthanc_dernier_patient(patients[patients.length-1])
            if dernier_patient
                id = dernier_patient["ID"]
                patient_id = dernier_patient["MainDicomTags"]["PatientID"]
                chemin = File.join(@url, "patients", id, "media")
                download = File.join(@download_dir, "#{patient_id}.zip")
                comm = "curl #{chemin} --output #{download}; wait"
                @value = %x( #{@xterm} "#{comm}" )
                @wasGood2 = $?
                #@wasGood = system( "#{xterm} '#{comm}'" )

                # Check if zipfile is present
                zipfiles = File.join(@download_dir, "*.zip")
                zips = Dir.glob(zipfiles)
                @res = (zips.length == 1) ? true : false
                @error_message = (zips.length == 1) ? nil : "ZIP file not found in #{@download_dir}"
            end
        end
    end


    #####################
    #   START MATLAB    #
    #####################
    def start_matlab
        @progression = get_progression(7, 13)
    end

    def start_matlab_ok
        @progression = get_progression(8, 13)
        @res = false

        #generateing startup.m
        script = "test"
        script = @cam1_script if session[:camera] == "1"
        script = @cam2_script if session[:camera] == "2"
        File.open(@startup_matlab, "w") do |f|
            f.puts("cd #{@scripts_matlab}")
            f.puts(script)
            f.close
        end
        startup = Dir.glob(@startup_matlab)
        res = (startup.length == 1) ? true : false
        @error_message = (startup.length == 1) ? nil : "Startup file not found (#{@startup_matlab})"
        
        # Starting matlab
        if res
            comm = "#{@matlab} ; wait"
            #comm = "top ; wait"
            @value = %x( #{@xterm} "#{comm}" )
            @wasGood2 = $?
            @res = true
        end
    end


    #####################
    #   ADD PDF TO DB   #
    #####################
    def add_pdf_to_db
        @progression = get_progression(9, 13)
    end

    def add_pdf_to_db_ok
        @progression = get_progression(10, 13)
        @res = false
        
        # ajouter patient
        patients = Patient.where(npp: session[:patient_id])
        if patients.size < 1
            patient = Patient.create(fullname: session[:patient_name], npp: session[:patient_id])
            if patient.save
                # ok
                indice_patient = patient.id
            else
                @error_message = "Impossible to create patient."
            end
        else
            indice_patient = patients.first.id
        end

        # ajouter spm
        spm = Spm.where(patient_id: session[:patient_id], study_date: session[:study_date])
        if spm.size < 1

            # check si pdfs existent
            dir = File.join(@depository, session[:patient_id], session[:study_date])
            spms = Dir.glob(File.join(dir, "*.pdf"))
            @error_message = (spms.length == 2) ? nil : "PDF files not found in #{dir}"

            # save 
            if (spms.length == 2)
                base = File.join('/Database', session[:patient_id], session[:study_date], @file_spm_base)
                mirror = File.join('/Database', session[:patient_id], session[:study_date], @file_spm_mirror)

                s = Spm.create(patient_id: indice_patient, study_date: session[:study_date], spm_base: base, spm_mirror: mirror)

                if s.save
                    # ok
                    @res = true
                else
                    @error_message = "Error while saving SPM into database."
                    if s.errors.any?
                        s.errors.full_messages.each do |message|
                            puts "===>>>> #{message}"
                        end
                    end
                end
            else
                @error_message = "Wrong number of PDF files in #{dir}."
            end
        else
            @error_message = "Another SPM already exists in the Database."
        end
    end


    #########################
    #   REMOVE DICOM ENTRY  #
    #########################
    def remove_dicom_entry
        @progression = get_progression(11, 13)
    end

    def remove_dicom_entry_ok
        @progression = get_progression(12, 13)
        @res = false

        # Vide le startup.m
        File.open(@startup_matlab, "w") do |f|
            f.puts("")
            f.close
        end
        startup = Dir.glob(@startup_matlab)
        res_ = (startup.length == 1) ? true : false
        @error_message = (startup.length == 1) ? nil : "Startup file not found (#{@startup_matlab})"

        if res_  
            # Supprime le patient du serveur DICOM
            remove_orthanc_patient(session[:orthanc_patient_id])
        end
    end


    #################
    #   FINISHED    #
    #################
    def finished
        @progression = get_progression(13, 13)
    end


    ################################################################################

    private

    def get_config
        # recupère depuis la config
        settings = Hash.new
        Setting.all.find_each do |setting|
            settings[setting[:key]] = setting[:value]
        end
        @depository = settings['depository']
        @file_spm_base = settings['file_spm_base']
        @file_spm_mirror = settings['file_spm_mirror']
        @url = settings['dicom_server_url']
        @xterm = settings['xterm']
        @download_dir = settings['download_directory']
        @matlab = settings['matlab']
        @startup_matlab = settings['startup_matlab']
        @scripts_matlab = settings['scripts_matlab']
        @cam1_script = settings['cam1_script']
        @cam2_script = settings['cam2_script']
    end

    def get_camera
        settings = Hash.new
        Setting.all.find_each do |setting|
            settings[setting[:key]] = setting[:value]
        end
        @cameras = Hash.new
        @cameras[1] = settings['cam1_nom']
        @cameras[2] = settings['cam2_nom']
        @camera = params[:camera] if params[:camera]
    end

    def get_progression(etape, etapes)
        (etape == etapes) ? 100 : ( (100 / (etapes) ) * (etape) )
    end

    ##### ORTHANC #####

    def request_api(url)
        #puts "***** CONTROLLER - request_api : #{url}"
        begin
            response = Excon.get(url)
        rescue => e
            @error_message = "#{url} => #{e}"
            return nil
        end
        if response.status != 200
            @error_message = "Response status : #{response.status}"
            return nil
        end
        JSON.parse(response.body)
    end

    def find_orthanc_patients
        request_api("http://127.0.0.1:8042/patients")
    end

    def find_orthanc_dernier_patient(id)
        request_api(File.join("http://127.0.0.1:8042/patients", id))
    end

    def find_orthanc_study(id)
        request_api(File.join("http://127.0.0.1:8042/studies", id))
    end

    def remove_orthanc_patient(id)
        comm = "curl -X DELETE http://127.0.0.1:8042/patient/#{id} ; wait"
        @value = %x( #{@xterm} "#{comm}" )
        @wasGood2 = $?

        puts "********************"
        puts "********************"
        puts "==> remove_orthanc_patient(#{id})"
        puts "********************"
        puts "COMM      : #{comm}"
        puts "@VALUE    : #{@value}"
        puts "@WASGOOD2 : #{@wasGood2}"
        puts "********************"
        puts "********************"

        @res = true
    end

end

app/views/matlab/_add_pdf_to_db.html.erb
<div class="container">

    <br>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>CAMERA</dt>
                        <dd>Getting camera... <span class="text-success material-icons" id="checked_camera">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>DICOM</dt>
                        <dd>Getting images... <span class="text-success material-icons" id="checked_zip">done</span></dd>
                        <dd>Reading header... <span class="text-success material-icons" id="checked_read">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <div class="p-2" id="button_next">
                    <a href="<%= remove_dicom_entry_path %>" 
                        class="btn btn-info"
                        role="button">
                        <span class="material-icons">navigate_next</span><br>
                        Next
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>MATLAB</dt>
                        <dd>Starting Matlab... <span class="text-success material-icons" id="checked_matlab">done</span></dd>
                        <dd>Adding PDF's to database... <span class="text-success material-icons" id="checked_pdf">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
        
    </div>
</div>

app/views/matlab/_read_dicom_header.html.erb
<div class="container">

    <br>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>CAMERA</dt>
                        <dd>Getting camera... <span class="text-success material-icons" id="checked_camera">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row">

        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>DICOM</dt>
                        <dd>Reading header... 
                            <span class="text-success material-icons" id="checked_read">
                                done
                            </span>
                            <span class="text-danger material-icons" id="error_read">
                                error
                            </span>
                        </dd>
                    </dl>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="d-flex justify-content-center">
                <div class="p-2" id="button_next">
                    <a href="<%= get_zip_path %>" 
                        class="btn btn-info"
                        role="button">
                        <span class="material-icons">navigate_next</span><br>
                        Next
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/matlab/_remove_dicom_entry.html.erb
<div class="container">

    <br>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>CAMERA</dt>
                        <dd>Getting camera... <span class="text-success material-icons" id="checked_camera">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>DICOM</dt>
                        <dd>Getting images... <span class="text-success material-icons" id="checked_zip">done</span></dd>
                        <dd>Reading header... <span class="text-success material-icons" id="checked_read">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <div class="p-2" id="button_next">
                    <a href="<%= finished_path %>" 
                        class="btn btn-info"
                        role="button">
                        <span class="material-icons">check_circle_outline</span><br>
                        Next
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>MATLAB</dt>
                        <dd>Starting Matlab... <span class="text-success material-icons" id="checked_matlab">done</span></dd>
                        <dd>Adding PDF's to database... <span class="text-success material-icons" id="checked_pdf">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <dl>
                        <dt>MISCELLANEOUS</dt>
                        <dd>Removing DICOM entry from server... <span class="text-success material-icons" id="checked_remove">done</span></dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>

app/views/matlab/add_pdf_to_db.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "add_pdf_to_db" %>

<script>
    document.getElementById("checked_pdf").hidden = true;
    document.getElementById("button_next").hidden = true;
    window.location.href="<%= add_pdf_to_db_ok_path %>";
</script>

app/views/matlab/add_pdf_to_db_ok.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "add_pdf_to_db" %>

<% if @error_message %>
    <div class="alert alert-danger">
        <%= @error_message %>
    </div>
<% end %>

<script>
    document.getElementById("checked_pdf").hidden = false;
    document.getElementById("button_next").hidden = false;
</script>

app/views/matlab/finished.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "finished" %>

<script>
    document.getElementById("checked_remove").hidden = false;
    document.getElementById("button_next").hidden = false;
</script>

app/views/matlab/get_zip.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "get_zip" %>

<script>
    document.getElementById("checked_zip").hidden = true;
    document.getElementById("button_next").hidden = true;
    document.getElementById("error_zip").hidden = true;
    window.location.href="<%= get_zip_ok_path %>";
</script>

app/views/matlab/get_zip_ok.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "get_zip" %>

<% if @error_message %>
    <div class="alert alert-danger">
        <%= @error_message %>
    </div>
<% end %>

<script>
    <% if @res %>
        document.getElementById("checked_zip").hidden = false;
        document.getElementById("error_zip").hidden = true;
        document.getElementById("button_next").hidden = false;
    <% else %>
        document.getElementById("checked_zip").hidden = true;
        document.getElementById("error_zip").hidden = false;
        document.getElementById("button_next").hidden = true;
    <% end %>
</script>

app/views/matlab/index.html.erb
<%= render "header" %>
<%= render "progress_bar" %>

<br>

<div class="container">

    <div class="card" style="width:400px">
    <div class="card-body">
        <h4 class="card-title">CAMERA</h4>
        <p class="card-text">Please click on the button corresponding to the camera of the study for wich you want to create a new SPM.</p>

        <div class="d-flex justify-content-center">

            <% @cameras.keys.each do |camera| %>
                <div class="p-2">
                    <a href="<%= matlab_path(camera: camera) %>" class="btn btn<%= "-outline" unless @camera == camera.to_s %>-info" role="button">
                        <span class="material-icons">center_focus_weak</span><br>
                        <%= camera %> - <%= @cameras[camera] %>
                    </a>
                </div>
            <% end %>

        </div>
    </div>
    </div>

    <br>

    <div class="card" style="width:400px">
    <div class="card-body">
        <h4 class="card-title">MATLAB</h4>
        <p class="card-text">Press the button below to run Matlab.</p>

        <div class="d-flex justify-content-center">

            <div class="p-2">
                <a href="<%= read_dicom_header_path(camera: @camera) %>" 
                    class="
                        btn 
                            btn<%= "-outline" unless @camera %>-success
                            <%= " disabled "  unless @camera %>
                        "
                    role="button">
                    <span class="material-icons">grid_view</span><br>
                    START
                </a>
            </div>

        </div>
    </div>
    </div>

</div>

app/views/matlab/read_dicom_header.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "read_dicom_header" %>

<script>
    document.getElementById("checked_read").hidden = true;
    document.getElementById("button_next").hidden = true;
    document.getElementById("error_read").hidden = true;
    window.location.href="<%= read_dicom_header_ok_path %>";
</script>

app/views/matlab/read_dicom_header_ok.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "read_dicom_header" %>

<% if @error_message %>
    <div class="alert alert-danger">
        STATUS : 
        <%= @error_message %>
    </div>
<% end %>

<% if @res %>
    <div class="alert alert-info">
        <p>
            <%= "#{session[:patient_name]}  (#{session[:patient_id]})  =>  Study date : #{session[:study_date]}"%>
        </p>
    </div>
<% end %>


<script>
    <% if @res %>
        document.getElementById("checked_read").hidden = false;
        document.getElementById("error_read").hidden = true;
        document.getElementById("button_next").hidden = false;
    <% else %>
        document.getElementById("checked_read").hidden = true;
        document.getElementById("error_read").hidden = false;
        document.getElementById("button_next").hidden = true;
    <% end %>
</script>

app/views/matlab/remove_dicom_entry.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "remove_dicom_entry" %>

<script>
    document.getElementById("checked_remove").hidden = true;
    document.getElementById("button_next").hidden = true;
    window.location.href="<%= remove_dicom_entry_ok_path %>";
</script>

app/views/matlab/remove_dicom_entry_ok.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "remove_dicom_entry" %>

<script>
    document.getElementById("checked_remove").hidden = false;
    document.getElementById("button_next").hidden = true;
    window.location.href="<%= finished_path %>";
</script>

app/views/matlab/start_matlab.html.erb
<%= render "header" %>
<%= render "progress_bar" %>
<%= render "start_matlab" %>

<script>
    document.getElementById("checked_matlab").hidden = true;
    document.getElementById("button_next").hidden = true;
    window.location.href="<%= start_matlab_ok_path %>";
</script>