config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  root "home#index"

  get "/matlab", to: "matlab#index"

  get "/get_zip", to: "matlab#get_zip"
  get "/get_zip_ok", to: "matlab#get_zip_ok"

  get "/read_dicom_header", to: "matlab#read_dicom_header"
  get "/read_dicom_header_ok", to: "matlab#read_dicom_header_ok"

  get "/start_matlab", to: "matlab#start_matlab"
  get "/start_matlab_ok", to: "matlab#start_matlab_ok"

  get "/add_pdf_to_db", to: "matlab#add_pdf_to_db"
  get "/add_pdf_to_db_ok", to: "matlab#add_pdf_to_db_ok"

  get "/remove_dicom_entry", to: "matlab#remove_dicom_entry"
  get "/remove_dicom_entry_ok", to: "matlab#remove_dicom_entry_ok"

  get "/finished", to: "matlab#finished"
  

  resources :spms
  resources :patients
  resources :settings

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
    validates :fullname, presence: true
    validates :npp, presence: true
    validates :npp, length: { is: 10 }
    validates :npp, uniqueness: true
    has_many :spms, dependent: :destroy
    validates_associated :spms
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :find_patient, only: [:show, :edit, :update, :destroy]

    def index
        @patients = Patient.order(:fullname).page(params[:page])

        # Local server and client IP addresses
        @admin_mode = false
        client_address = request.remote_ip
        ips = Socket.ip_address_list
        ips.each do |ip|
            @admin_mode = true if ip.ip_address == client_address
        end
        
    end

    def show
    end

    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.create(patient_params)
        if @patient.save
            flash[:notice] = "Patient created"
            redirect_to patients_path
        else
            flash[:alert] = "Error(s)"
            render :new
        end
    end

    def edit
    end

    def update
        if @patient.update(patient_params)
            flash[:notice] = "Patient updated."
            redirect_to patients_path
        else
            render :edit
        end
    end

    def destroy
        @patient.destroy
    end

    private

    def patient_params
        params.require(:patient).permit(:fullname, :npp)
    end

    def find_patient
        @patient = Patient.find(params[:id])
    end
    
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with model: @patient, local: true do |form| %>

    <% if @patient.errors.any? %>
        <strong>WARNING</strong>
        <ul>
            <% @patient.errors.full_messages.each do |message| %>
                <li class="bg-danger"><%= message %></li>
            <% end %>
        </ul>
    <% end %>

    
    <!-- Fullname -->
    <p>
        <%= form.label :fullname %><br>
        <%= form.text_field :fullname, placeholder: "Firstname LASTNAME" %>
    </p>

    <!-- NPP -->
    <p>
        <%= form.label :npp %><br>
        <%= form.text_field :npp, placeholder: "YYMMDDXX00" %>
    </p>

    <p>
        <%= form.submit class: "btn btn-primary" %>
    </p>

<% end %>

app/views/patients/_patient.html.erb
<tr id="patient_<%= patient.id %>">

    <td>
        <% if (patient.npp[6].upcase == "M") %>
            <span class="material-icons text-primary">male</span>
        <% elsif (patient.npp[6].upcase == "F") %>
            <span class="material-icons text-danger">female</span>
        <% else %>
            <span class="material-icons text-warning">transgender</span>
        <% end %>

        <% split = patient.fullname.split("^") %>
        <% nom = "#{split[0].upcase} #{split[1].titleize if split[1]}" %>
        <%= patient_split_fullname(patient) %>
    </td>

    <td><%= patient.npp %></td>

    <% if @admin_mode %>
        <td><a href="<%= edit_patient_path(patient) %>" class="btn btn-info btn-sm" role="button"
                data-toggle="tooltip" title="Edit patient">
                <span class="material-icons">edit</span>
            </a></td>
        
        <td><%= link_to '<span class="material-icons" data-toggle="tooltip" title="Delete">clear</span>'.html_safe, 
                patient_path(patient),
                method: :delete,
                remote: true,
                data: { confirm: "Delete patient #{patient.fullname} ?" },
                class: "btn btn-danger btn-sm" 
            %>
        </td>
    <% end %>

    <td><a href="<%= spms_path(patient_id: patient) %>" class="btn btn-info btn-sm" role="button"
            data-toggle="tooltip" title="View SPM's">
            <span class="material-icons">list</span>
        </a></td>
</tr>

app/views/patients/_patients.html.erb
<!-- Table paginée -->
<p><%= paginate @patients, remote: true %></p>
<table class="table table-striped">
    <tr>
        <th>Fullnames</th>
        <th>NPP</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
<%= render @patients %>
</table>
<p><%= paginate @patients, remote: true %></p>

app/views/patients/destroy.js.erb
$("#patient_<%= @patient.id %>").remove();

app/views/patients/edit.html.erb
<h3>Edit Patient</h3>
<%= render "form" %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<% if @admin_mode %>
    <p>
        <a href="<%= new_patient_path %>" class="btn btn-secondary" role="button"
            data-toggle="tooltip" title="New Patient">
            <span class="material-icons">person_add</span>
        </a>
    </p>
<% end %>

<div id="patients">
    <%= render 'patients' %>
</div>

app/views/patients/index.js.erb
$("#patients").html("<%= j render "patients" %>");

app/views/patients/new.html.erb
<h3>New Patient</h3>
<%= render "form" %>