config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#index"
  root "home#index"

  get "/matlab", to: "matlab#index"

  get "/get_zip", to: "matlab#get_zip"
  get "/get_zip_ok", to: "matlab#get_zip_ok"

  get "/read_dicom_header", to: "matlab#read_dicom_header"
  get "/read_dicom_header_ok", to: "matlab#read_dicom_header_ok"

  get "/start_matlab", to: "matlab#start_matlab"
  get "/start_matlab_ok", to: "matlab#start_matlab_ok"

  get "/add_pdf_to_db", to: "matlab#add_pdf_to_db"
  get "/add_pdf_to_db_ok", to: "matlab#add_pdf_to_db_ok"

  get "/remove_dicom_entry", to: "matlab#remove_dicom_entry"
  get "/remove_dicom_entry_ok", to: "matlab#remove_dicom_entry_ok"

  get "/finished", to: "matlab#finished"
  

  resources :spms
  resources :patients
  resources :settings

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<p class="footer text-center">Copyright @2021 PETScan ULB Erasme</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <a class="navbar-brand" href="<%= root_path %>">SPM-DB</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="<%= patients_path %>"
                data-toggle="tooltip" title="Patients">
                <span class="material-icons">people</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<%= spms_path %>"
                data-toggle="tooltip" title="All SPM's">
                <span class="material-icons">list</span>
            </a>
        </li>

        <% if @admin_mode %>
            <li class="nav-item">
                <a class="nav-link" href="<%= matlab_path %>"
                    data-toggle="tooltip" title="New SPM">
                    <span class="material-icons">create_new_folder</span>
                </a>
            </li>
        <% end %>

    </ul>

    <% if @admin_mode %>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item" style="float:right">
                <a class="nav-link" href="<%= settings_path %>"
                    data-toggle="tooltip" title="Settings">
                    <span class="material-icons">settings</span>
                </a>
            </li>
        </ul>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpmDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- NAVBAR -->
    <%= render 'layouts/navbar' %>

    <div class="container-fluid" style="margin-top:80px">
      <!-- HEADER -->
      <%= render 'layouts/header'%>

      <!-- FLASH -->
      <div class="container">
          <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: key %>
          <% end %>
      </div>

      <!-- YIELD -->
      <%= yield %>

      <!-- Admin Mode -->
      <div class="container">
        <div class="m-5  float-right mx-auto <%= @admin_mode ? 'bg-success text-white' : 'bg-light text-dark' %>  text-center" style="width:400px">
          <small>
            <% unless @admin_mode %>
              Remote Access. User mode.
            <% else %>
              Local Access. Admin mode.
            <% end %>
          </small>
        </div>
      </div>

      <!-- FOOT -->
      <%= render 'layouts/footer'%>
    </div>

  </body>
</html>